### ISSUE TITLE
iPhone X 13.3 Checkra1n support

### ISSUE THREAD

**Issue by endercypher** [bazad/memctl#14]
This is what’s happening, 
Enders-iPhone-X:/var/mobile root# memctl         
memctl> fc AppleMobileFileIntegrity              
warning: could not find _bzero_phys              
warning: could not find _pthread_kext_register   
warning: could not find __FREE                   
Assertion failed: (kr == KEXT_SUCCESS), function ksim_set_pc, file src/libmemctl/arm64/ksim.c, line
307.                                             
deinitialized                                    
Abort trap: 6

**Comment by bazad** [comment]
Unfortunately memctl is rather outdated at the moment, and does not work on modern stripped kernelcaches, since the symbol finders need to be updated and the assumptions I made about heap behavior no longer hold. Realistically, I won't have time to update it for awhile, as I'll be focusing on updating [KTRW](https://github.com/googleprojectzero/ktrw) for checkra1n. Is there a specific feature you are looking for?

**Comment by endercypher** [comment]
I was mainly looking at the ability to call kernel functions & find them for use such as serial communications etc.

**Comment by bazad** [comment]
Ah, I see. I'm not aware of a quick and easy way to do that at the moment without writing some code.

**Comment by endercypher** [comment]
Even if something on KTRW helped, also I’ve got a kernel cache that’s got some symbols but it’s 13.3 iPhone X, if you need any help testing with KTRW I’d be more than happy to help.

**Comment by endercypher** [comment]
Also, couldn’t you in theory make a PongoOS Module for checkra1n to load your GBD kext?

**Comment by bazad** [comment]
Yes, my plan is to convert KTRW into a pongoOS module.

**Comment by endercypher** [comment]
What is the time that you think it might take for that to be finished?

**Comment by endercypher** [comment]
If there was support for the iPhone X on iOS 13.3 aka the iPhone 10,6 & 10,3 on iOS 13.3 for KTRW that would be wonderful.
